### ISSUE TITLE
Key parse error

### ISSUE THREAD

**Issue by vilyansky** [plapointe6/EspHtmlTemplateProcessor#1]
In html line contains a space symbols in text, library have a parse error.
For example:
`<tr><td>Test template IP</td><td><input name="TestTemplateIP" size=15 maxlength=15 value={{test_template1}}></input></td></tr>`
`key` have parsed as `{{test_template` not a `test_template`.

**Comment by plapointe6** [comment]
thank you for raising this issue, I will get into that soon.

**Comment by plapointe6** [comment]
Hello,

I am trying to reproduce your issue, but all my testing worked.
Maybe I need more information to reproduce the issue ?

The HTML file I parsed : 
```html
<!DOCTYPE html>
<html>
<body>

<h2>Basic HTML Table</h2>

<table style="width:100%">
  <tr><td>Test template IP</td><td><input name="TestTemplateIP" size=15 maxlength=15 value={{test_template1}}></input></td></tr>
</table>

</body>
</html>
```

The output it gives to me : 
```html
<!DOCTYPE html>
<html>
<body>

<h2>Basic HTML Table</h2>

<table style="width:100%">
  <tr><td>Test template IP</td><td><input name="TestTemplateIP" size=15 maxlength=15 value=test></input></td></tr>
</table>

</body>
</html>
```

And my key parsing function : 
```c++
String keyProcessor(const String& key)
{
  if (key == "test_template1")
    return "test";
  else
    return "NF";
}
```

Any additionnal information would be appreciated.

**Comment by vilyansky** [comment]
Oh, thanks. I have rewrited large amount of code in my project then, but I will trying to reproduce this error in a few days.

**Comment by pat1** [comment]
The problem is not html line contains a space symbols; is the position found for {{key}}.
You can find the patch here: 
https://github.com/r-map/rmap/commit/7f2b906dbe389ae23891b9ef102daaafe497750b#diff-db38275ef881dceb680e19ff6467bc32

You have to put those two line of code outside the if block

  buffer[0] = ch;
  index = 1;

**Comment by plapointe6** [comment]
Thanks for the informations, I will take a look into this.
I made some testing when I created this lib and the issue did not appeared.

I am currently developping a project that use this lib, no issue so far, but I am on an early stage.

@pat1 : if you are able to send me a sample of an HTML page where the issue occurs, It will be easyer for me to test your proposed changes and apply the patch.

**Comment by pat1** [comment]
The key have to be at the end of a buffer.
I have the error with this file:
https://github.com/r-map/rmap/blob/master/arduino/sketchbook/domotica/measure/data/rreport.html

**Comment by plapointe6** [comment]
Great ! Thanks

**Comment by plapointe6** [comment]
I applied the proposed patch from @pat1, thanks.
