### ISSUE TITLE
zero length return value

### ISSUE THREAD

**Issue by cmstephan** [plapointe6/EspHtmlTemplateProcessor#2]
Hi, 
it seems that the processor runs into an issue if the returned string in indexKeyProcessor has a zero length. 
The html site did not get rendered returned if the return value of a key is "". At least in my program. 
Chritstopher

**Comment by plapointe6** [comment]
Hi,
I made a fix, could you test if it works now ?
Thanks !

**Comment by plapointe6** [comment]
I tested the fix, it works :)
